### PR TITLE
Added Unknown to OperationContent so that the parsing does not fail if the library is not up to date on operation types

### PR DESCRIPTION
**Pull request by Wicpar**
Fix to the parsing error when unknown operations contents appear in blocks.

- Added Unknown to OperationContent so that the parsing does not fail if the library is not up to date on operation types

### CODE REVIEW

**Comment by Wicpar** [comment]
i would also note that there is no reason to use an untagged enum as it is tagged with kind. What is the rationale behind it ?

**Comment by RomarQ** [comment]
> i would also note that there is no reason to use an untagged enum as it is tagged with kind. What is the rationale behind it ?

I agree, using `tag = "kind"` instead of `untagged` is preferable here, we will have a look at it.

At the time I believe it was because of the new operations being added, some of them got renamed and ended up being removed on mumbai upgrade.

**Comment by Wicpar** [comment]
Indeed if renames are possible it does make sense to keep them as untagged. The only risk is the collision of two schemas. Whichever is more risky should determine what to keep.

**Comment by RomarQ** [comment]
Thanks for the contribution :+1: .

**Pull request merged**
